name: networth-pull-request
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
      - name: Install Playwright
        run: playwright install
      - name: Run Tests
        run: pytest
